---
title: "CV"
author: "Eric J. Ward"
email: eric.ward@noaa.gov
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
jobtitle: Statistician & Research Biologist
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: no
phone: 206-302-1745
address: Northwest Fisheries Science Center · 2725 Montlake Blvd E · Seattle, WA
updated: no
urlcolor: blue
web: eric-ward.github.io
---

# Education

*University of Washington*, Ph.D. Aquatic and Fishery Sciences \hfill 2003-2006
\newline - *Committee:* Ray Hilborn (advisor), Andre Punt, Tim Essington

*Montana State University*, MSc Biology \hfill 2000-2003
\newline - *Advisor:* Dan Goodman

*University of California San Diego*, BSc Ecology and Evolution \hfill 1995-1999


# Employment

*Statistican* Northwest Fisheries Science Center, NMFS (NOAA) \hfill 2009 - present

*Affiliate Associate Professor* University of Washington (SAFS) \hfill 2013 - present

*Post-doctoral researcher* National Research Council \hfill 2007 - 2008

*Stock assessment scientist* Wellington, New Zealand \hfill Spring 2005

*Graduate research assistant* University of Washington \hfill 2003 - 2006

# Journal Articles (peer - reviewed)

>70. **E.J. Ward**, S.C. Anderson, A.O. Shelton, R.E. Brenner, M.D. Adkison, A.H. Beaudreau, J.T. Watson, J.C. Shriver, A.C. Haynie, and B.C. Wiliams. Effects of increased specialization on revenue of Alaskan salmon fishers over four decades. *Journal of Applied Ecology, in press*

>69. Chasco, B., I.C. Kaplan, A.C. Thomas, A. Acevedo-Gutiérrez, D.P. Noren, M.J. Ford, M.B. Hanson, J. Scordino, S. Jeffries, K.N. Marshall, A.O. Shelton, C. Matkin, B. Burke, and **E.J. Ward**. Competing tradeoffs between increasing marine mammal predation and fisheries harvest of Chinook salmon. *Nature Scientific Reports, in press*

>68. Anderson, S.C., **E.J. Ward**, A.O. Shelton, M.D. Adkison, A.H. Beaudreau, R.E. Brenner, A.C. Haynie, J.C. Shriver, J.T. Watson, and B.C. Williams. Benefits and risks of diversification for individual fishers. *Proceedings of the National Academy of Sciences*, 114(40): 10797–10802. [link]
(http://www.pnas.org/content/114/40/10797.full)

>67. Linder, H., J.K. Horne, and **E.J. Ward**. 2017. Modeling baseline conditions of ecological indicators: Marine renewable energy environmental monitoring. *Ecological Indicators*, 83: 178-191. [link](https://www.sciencedirect.com/science/article/pii/S1470160X17304284)

>66. Deacy, W.W., J.B. Armstrong, W.B Leacock, C. Robbins, D.D. Gustine, **E.J. Ward**, J.A. Erlenbach, J.A. Stanford. Phenological synchronization disrupts trophic interactions between Kodiak brown bears and salmon. *Proceedings of the National Academy of Sciences*, 114(39): 10432–10437. [link](http://www.pnas.org/content/114/39/10432.abstract)

>65. Shelton, A.O., M.E. Hunsicker, **E.J. Ward**, B.E. Feist, R. Blake, C.L. Ward, B.C. Williams, J.T. Duffy-Anderson, A.B. Hollowed, A.C. Haynie. 2017. Spatio-temporal models reveal subtle changes to demersal communities following the Exxon Valdez oil spill. *ICES Journal of Marine Science, fsx079* [link](https://academic.oup.com/icesjms/article-abstract/doi/10.1093/icesjms/fsx079/3852237?redirectedFrom=fulltext)

>64. **Ward, E.J.**, M. Adkison, J. Couture, S.C. Dressel, M.A. Litzow, S. Moffitt, T. Hoem Neher, J. Trochta, and R. Brenner. 2017. Evaluating signals of oil spill impacts, climate, and species interactions in Pacific herring and Pacific salmon populations in Prince William Sound and Copper River, Alaska. *PLOS ONE*, 12(3): e0172898. [link](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0172898)

>63. Hussey, N., J. DiBattista, J. Moore, **E.J. Ward**, A. Fisk, S. Kessel, T. Guttridge, K. Feldheim, B. Franks, S. Gruber, O. Weideli, and D. Chapman. 2017. Risky business for a marine predator? Testing the influence of foraging strategies on size and growth rate under natural conditions. *Proceedings of the Royal Societety Series B*, 284(1852): 20170166. [link](http://rspb.royalsocietypublishing.org/content/284/1852/20170166)

>62. Chasco, B., I.C. Kaplan, A. Thomas, A. Acevedo-Gutiérrez, D.P. Noren, M.J. Ford, M.B. Hanson, J. Scordino, S.J. Jeffries, S.F. Pearson, K.N. Marshall, and **E.J. Ward**. 2017. Estimates of Chinook salmon consumption in Washingon State inland waters by four marine mammal predators from 1970 – 2015. *Canadian Journal of Fisheries and Aquatic Sciences*, 74(8): 1173-1194. [link](https://doi.org/10.1139/cjfas-2016-0203) 

>61. Moriarty, P., T.E. Essington, and **E.J. Ward**. 2017. A novel method to estimate prey contributions to predator diets. *Canadian Journal of Fisheries and Aquatic Sciences*, 74: 168-177.  [link](http://www.nrcresearchpress.com/doi/abs/10.1139/cjfas-2016-0149#.WDIPj-ErLBI)

>60. Armstrong, J.B., **E.J. Ward**, D.E. Schindler, and P.J. Lisi. 2016. Adaptive capacity at the northern front: sockeye salmon behaviorally thermoregulate during novel exposure to warm temperatures. *Conservation Physiology*, 4(1): cow039. [link](http://conphys.oxfordjournals.org/content/4/1/cow039.full)

>59. Boyd, C., D.P. DeMaster, R.S. Waples, **E.J. Ward**, and B.L. Taylor. 2016. Consistent Extinction Risk Assessment under the U.S. Endangered Species Act. *Conservation Letters*, 10(3): 328-336. [link](http://onlinelibrary.wiley.com/doi/10.1111/conl.12269/abstract)

>58. Stier, A.C., J.F. Samhouri, M. Novak, K.N. Marshall, **E.J. Ward**, R.D. Holt, and P.S. Levin. Ecosystem context and historical contingency in apex predator recoveries. *Science Advances*, 5(2): e1501769. [link](http://advances.sciencemag.org/content/2/5/e1501769)

>57. Adams, J.B., I.C. Kaplan, B. Chasco, K.N. Marshall, A. Acevedo-Gutiérrez, and **E.J. Ward**. 2016. A century of Chinook salmon consumption by marine mammal predators in the Northeast Pacific Ocean. *Ecological Informatics*, 34: 44-51. [link](http://www.sciencedirect.com/science/article/pii/S1574954116300383)

>56. Thorson, J.T., M.L. Pinsky, and **E.J. Ward**. 2016. Model-based inference for estimating shifts in species distribution, area occupied, and center of gravity. *Methods in Ecology and Evolution*, 7: 990-1002.  [link](http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12567/abstract)

>55. Jorgensen, J.C., **E.J. Ward**, M.D. Scheuerell, and R.W. Zabel. 2016. Assessing spatial covariance among time series of abundance. *Ecology and Evolution*, 6: 2472–2485. [link](http://onlinelibrary.wiley.com/doi/10.1002/ece3.2031/full)

>54. **Ward, E.J.**, M.E. Dahlheim, J.M. Waite, C.K. Emmons, K.N. Marshall, B.E. Chasco, K.C. Balcomb III. 2016. Long distance migration of prey synchronizes demographic rates of top predators across broad spatial scales. *Ecosphere*, 7(2): e01276. [link](http://onlinelibrary.wiley.com/doi/10.1002/ecs2.1276/full)

>53. Ono, K., A.O. Shelton, **E.J. Ward**, J.T. Thorson, B.E. Feist, and R. Hilborn. 2016. Space-time investigation of the effects of fishing on fish populations. *Ecological Applications*, 26(2): 392-406. [link](http://onlinelibrary.wiley.com/doi/10.1890/14-1874/abstract)

>52. Marshall, K.N., A.C. Stier, J.F. Samhouri, R.P. Kelly, and **E.J. Ward**. 2016. Conservation challenges of predator recovery. *Conservation Letters*, 9: 70-78. [link](http://onlinelibrary.wiley.com/store/10.1111/conl.12186/asset/conl12186.pdf?v=1&t=iq1gglmt&s=e1437a456d13fb1f83168858e8fa8705496f34ed) 

>51. Galloway, A.W.E., M.T. Brett, G.W. Holtgrieve, **E.J. Ward**, A.P. Ballantyne, C.W. Burns, M.J. Kainz, D.C. Muller-Navarra, J. Persson, J.L. Ravet, U. Strandberg, S.J. Taipale. 2015. A Fatty acid based Bayesian approach for inferring diet in aquatic consumers. *PLoS ONE*, 10(6): e0129723. [link](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0129723)

>50. P.A.H. Westley, A.H. Dittman, **E.J. Ward**, and T. Quinn. 2015. Signals of climate, conspecific density, and watershed features in patterns of homing and dispersal by Pacific salmon. *Ecology*, 96: 2823–2833. [link](http://onlinelibrary.wiley.com/doi/10.1890/14-1630.1/abstract)

>49. **Ward, E.J.**, Y.W. Lee, K. Ono, A.O. Shelton, and J.T. Thorson. 2015. Using spatiotemporal species distribution models to identify temporally evolving hotspots of species co-occurrence. *Ecological Applications*, 25: 2198-2209. [link](http://onlinelibrary.wiley.com/doi/10.1890/15-0051.1/abstract)

>48. Bjorkland, R.K., S. Pearson, S. Jeffries, M. Lance, A. Acevedo-Gutierrez, and **E.J. Ward**. 2015. Stable isotope mixing models elucidate sex and size effects on the diet of a generalist marine predator. *Marine Ecology Progress Series*, 526: 213-225. [link](http://www.int-res.com/abstracts/meps/v526/p213-225/)

>47. **Ward, E.J.**, J.H. Anderson, T.J. Beechie, G.R. Pess, and M.J. Ford. 2015. Increasing hydrologic variability threatens depleted anadromous fish populations. *Global Change Biology*, 21: 2500-2509. [link](http://onlinelibrary.wiley.com/doi/10.1111/gcb.12847/abstract)

>46. Sergeant, C.J., J.B. Armstrong, and **E.J. Ward**. 2015. Predator-prey migration phenologies remain synchronised in a warming catchment. *Freshwater Biology*, 60: 724-732. [link](http://onlinelibrary.wiley.com/doi/10.1111/fwb.12524/abstract)

>45. Thorson, J.T., A.O. Shelton, **E.J. Ward**, and H. Skaug. 2015. Geostatistical delta-generalized linear mixed models improve precision for estimated abundance indices for West Coast groundfishes. *ICES Journal of Marine Science*, 72: 1297-1310. [link](http://icesjms.oxfordjournals.org/content/early/2015/01/13/icesjms.fsu243.abstract)

>44. **Ward, E.J.**, K.N. Marshall, A. Sedgley, T. Ross, T. Hass, S.F. Pearson, G. Joyce, N.J. Hamel, P.J. Hodum, R. Faucett. 2015. Using citizen-science data to identify local hotspots of seabird occurrence. *PeerJ*, 2: e704. [link](https://peerj.com/articles/704/)

>43. Thorson, J.T., H. Skaug, K. Kristensen, A.O. Shelton, **E.J. Ward**, J. Harms, and J. Benante. 2015. The importance of spatial models for estimating the type and strength of density dependence. *Ecology*, 96: 1202–1212. [link](http://onlinelibrary.wiley.com/doi/10.1890/14-0739.1/full)

>42. Thorson, J.T., J.M. Cope, K.M. Kleisner, J.F. Samhouri, A.O. Shelton, and **E.J. Ward.** 2015. Giants’ shoulders 15 years later: Lessons, challenges, and guidelines in fisheries meta-analysis. *Fish and Fisheries*, 16: 342-361. [link](http://onlinelibrary.wiley.com/doi/10.1111/faf.12061/abstract)

>41. Phillips, D.L., R. Inger, S. Bearhop, A.L. Jackson, J.W. Moore, A.C. Parnell, B.X. Semmens, and **E.J. Ward**. 2014. Best practices for use of stable isotope mixing models in
food-web studies. *Canadian Journal of Zoology*, 92: 823-835. [link](http://www.nrcresearchpress.com/doi/pdf/10.1139/cjz-2014-0127)

>40. Anlauf-Dunn, K., **E.J. Ward**, and M. Strickland. 2014. Habitat connectivity, complexity and quality: Predicting adult coho salmon occupancy and abundance. *Canadian Journal of Fisheries and Aquatic Sciences*, 71: 1864-1876. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/cjfas-2014-0162#.V3RNapMrLBI)

>39. Chasco, B., **E.J. Ward**, C. Rabe, R. Orme, R. Kinzer, J. Vogel, J. Hesse, P. Kucera. 2014. Evaluating the accuracy and precision of multiple abundance estimators using state-space models: a case study for a threatened population of Chinook salmon in Johnson Creek, Idaho. *North American Journal of Fisheries Management*, 34(5): 945-954. [link](http://afs.tandfonline.com/doi/abs/10.1080/02755947.2014.926302#.V3RNhJMrLBI)

>38. Shelton, A.O., J.T. Thorson, **E.J. Ward**, and B.E. Feist. 2014. Spatial semi-parametric models improve estimates of species abundance and distribution. *Canadian Journal of Fisheries and Aquatic Sciences*, 71: 1655-1666. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/cjfas-2013-0508#.V3P7dpMrLBI)

>37. **Ward, E.J.**, E.E. Holmes, J.T. Thorson, and B. Collen. 2014. Complexity is costly: a meta-analysis of parametric and non-parametric methods for short-term population forecasting. *Oikos*, 123(6): 652-661. *Selected for Editor’s Choice June 2014*. [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0706.2014.00916.x/abstract)

>36. J.T. Thorson and **E.J. Ward.** 2014. Accounting for vessel effects when standardizing catch rates from cooperative surveys. *Fisheries Research*, 155:  168-176. [link](http://www.sciencedirect.com/science/article/pii/S0165783614000836)

>35. Nosrati, K., G. Govers, B.X. Semmens, and **E.J. Ward**. 2014. A mixing model to incorporate uncertainty in sediment fingerprinting. *Geoderma*, 217/218: 173–180. [link](http://www.sciencedirect.com/science/article/pii/S0016706113004308)

>34. Bodey, T., **E.J. Ward**, R.A. Phillips, R.A.R. McGill, and S. Bearhop. 2014. Species versus guild level differentiation revealed across the annual cycle by isotopic niche examination. *Journal of Animal Ecology*, 83: 470-478. [link](http://onlinelibrary.wiley.com/doi/10.1111/1365-2656.12156/abstract)

>33. Hampton, S.E., E.E. Holmes, D.E. Pendleton, L.P. Scheef, M.D. Scheuerell, and **E.J. Ward**. 2013. Quantifying effects of abiotic and biotic drivers on community dynamics with multivariate autoregressive (MAR) models. *Ecology*, 94(12): 2663–2669. *Recommended by Faculty of 1000 Biology* [link](http://onlinelibrary.wiley.com/doi/10.1890/13-0996.1/abstract)

>32. B.X. Semmens, **E.J. Ward**, A.C. Parnell, D.L. Phillips, S. Bearhop, R. Inger, A.L. Jackson, and J.W. Moore. 2013. Statistical basis and outputs of stable isotope mixing models: Comment on Fry 2013. *Marine Ecology Progress Series*, 490: 285-289. [link](http://www.int-res.com/abstracts/meps/v490/p285-289/)

>31. M.B. Hanson, C. Emmons, **E.J. Ward**, J. Nystuen, and M. Lammers. 2013. Assessing the coastal occurrence of endangered killer whales using autonomous passive acoustic recorders. *Journal of the Acoustical Society of America*, 134(5): 3486-3495. [link](http://www.ncbi.nlm.nih.gov/pubmed/24180759)

>30. Parnell, A.C., D.L. Phillips, S. Bearhop, A.L. Jackson, B.X. Semmens, **E.J. Ward**, J.W. Moore, and R.L. Inger. 2013. Bayesian Stable Isotope Mixing Models. *Environmetrics*, 24(6): 387-399. [link](http://onlinelibrary.wiley.com/doi/10.1002/env.2221/abstract)

>29. Thorson, J.T. and **E.J. Ward.** 2013. Accounting for space-time interactions in index standardization models. *Fisheries Research*, 147: 426-433. [link](http://www.sciencedirect.com/science/article/pii/S0165783613000805)

>28. Holtgrieve, G.W., M.E. Arias, K.N. Irvine, **E.J. Ward**, M. Kummu, J. Koponen, and J.E. Richey. 2013. Patterns of ecosystem metabolism in the Tonle Sap Lake, Cambodia with links to capture fisheries. *PLoS One*, 8(8):e71395, 1-11. [link](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0071395)

>27. Van Daele, M.B., B.X. Semmens, **E.J. Ward**, L.J. Van Daele, W.B. Leacock, C.T. Robbins. 2013. Salmon consumption by Kodiak brown bears (Ursus arctos middendorffi) with ecosystem management implications. *Canadian Journal of Zoology*, 91: 164-174. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/cjz-2012-0221#.V3P5upMrLBI)

>26. Westley, P., **E.J. Ward**, and I. Fleming. 2013. Fine-scale local adaptation in an invasive freshwater fish has evolved in contemporary time. *Proceedings of the Royal Society*, Series B., 280(751). [link](http://rspb.royalsocietypublishing.org/content/280/1751/20122327)

>25. **Ward, E.J.**, G.R. Pess, K. Anlauf-Dunn, and C.E. Jordan. 2012. Applying time series models with spatial correlation to identify the scale of variation in habitat metrics related to threatened coho salmon (Oncorhynchus kisutch) in the Pacific Northwest. *Canadian Journal of Fisheries and Aquatic Sciences*, 69(11):  1773-1782. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/f2012-096#.V3P5fJMrLBI)

>24. **Ward, E.J.**, P.S. Levin, M.M. Lance, S.J. Jeffries, and A. Acevedo-Gutiérrez. 2012. Integrating diet and movement data to identify hot spots of predation risk and areas of conservation concern for endangered species. *Conservation Letters*, 5(1): 27-37 dpi: 10.1111/j.1755- 263X.2011.00210.x. [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1755-263X.2011.00210.x/abstract)

>23. Holmes, E.E., **E.J. Ward**, and K. Wills. 2012. MARSS: multivariate autoregressive state-space models for analyzing time series data. *R Journal*, 4(1): 11-19. [link](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Holmes~et~al.pdf)

>22. Holtgrieve, G., D.E. Schindler, W.O. Hobbs, P.R. Leavitt, **E.J. Ward**, L. Bunting, G. Chen, B.P. Finney, I. Gregory-Eaves, S. Holmgren, M.J. Lisac, P.J. Lisi, K. Nydick, L.A. Rogers, J.E. Saros, D.T. Selbie, M.D. Shapley, P.B. Walsh, and A.P. Wolfe. 2011. A coherent signature of anthropogenic nitrogen deposition to remote watersheds of the Northern Hemisphere. *Science*, 16: 1545-1548. doi: 10.1126/science.1212267. [link](http://science.sciencemag.org/content/334/6062/1545)

>21. Yeakel, J.D., M. Novak, P.R. Guimarães Jr., N.J. Dominy, P.L. Koch, **E.J. Ward**, J.W. Moore, and B.X. Semmens. 2011. Merging resource availability with isotope mixing models: the role of neutral interaction assumptions. *PLoS ONE*, 6(7): e22015. [link](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0022015)

>20. Anderson, J., **E.J. Ward**, and S.M. Carlson. 2011. A model for estimating the minimum number of offspring to sample in studies of reproductive success. *Journal of Heredity*, 102(5): 567-576. [link](http://jhered.oxfordjournals.org/content/early/2011/06/22/jhered.esr060.full)

>19. Berntson, E.A., R.W. Carmichael, M.W. Flesher, **E.J. Ward**, and P. Moran. 2011. Diminished reproductive success of steelhead from a hatchery supplementation program (Little Sheep Creek, Imnaha Basin, Oregon). *Transactions of the American Fisheries Society*, 140(3): 685-698. [link](http://www.tandfonline.com/doi/abs/10.1080/00028487.2011.584489#.V3P4uZMrLBI)

>18. Francis, T.B., D.E. Schindler, G.W. Holtgrieve, E. Larson, M.D. Scheuerell, B.X. Semmens, and **E.J. Ward**. 2011. Habitat structure determines resource use by zooplankton in temperate lakes. *Ecology Letters*, 14: 364-372. [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1461-0248.2011.01597.x/abstract)

>17. **Ward, E.J.**, Semmens, B.X., Phillips, D.L., Moore, J.W., and Bouwes, N. 2011. A quantitative approach to combine sources in stable isotope mixing models. *Ecosphere*, 2(2):art19. [link](http://onlinelibrary.wiley.com/store/10.1890/ES10-00190.1/asset/ecs210001901.pdf?v=1&t=iq13qr4g&s=c58f7ce2c22a8f7821ac98a3c02651dc5377ff65)
*joint 1st authorship*

>16. **Ward, E.J.**, Semmens, B.X., Holmes, E.E., and K.C. Balcomb. 2011. Effects of multiple levels of social organization on survival and abundance. *Conservation Biology*, 25(2): 350-355.  [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1523-1739.2010.01600.x/abstract)

>15. **Ward, E.J.**, Zerbini, A.N., Engel, M.E., Kinas, P.G. and Andriolo, A. 2011. Estimates of population growth rates of humpback whales (Megaptera novaeangliae) in the wintering grounds off the coast of Brazil (Breeding Stock A). *J. Cet Res. Manage.* (Special Issue), 3: 145-149.

>14. Zerbini, A.N., **E.J. Ward**, Engel, M.E., Kinas, P.G. and Andriolo, A. 2009. A Bayesian assessment of the conservation status of humpback whales (Megaptera novaeangliae) in the Western South Atlantic (Breeding Stock A). *J. Cet Res. Manage.*, SC/58/SH02.

>13. **Ward, E.J.**, B.X. Semmens, and D.E. Schindler. 2010. Including source uncertainty and prior information in the analysis of stable isotope mixing models. *Environmental Science & Technology*, 44(12): 4645-4650. [link](http://pubs.acs.org/doi/abs/10.1021/es100053v)

>12. Williamson, K.S., A.R. Murdoch, T.N. Pearsons, **E.J. Ward**, and M.J. Ford. 2010. Factors influencing the relative fitness of hatchery and wild spring Chinook salmon in the Wenatchee River, Washington, USA. *Canadian Journal of Fisheries and Aquatic Sciences*, 67: 1840-1851. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/F10-099#.V3P0WZMrLBI)

>11. Warren, D.R., M.M. Mineau, **E.J. Ward**, and C.E. Kraft. 2010. Relating fish biomass to habitat and chemistry in headwater streams of the northeastern United States. *Environmental Biology of Fishes*, 88: 51-62. [link](http://link.springer.com/article/10.1007%2Fs10641-010-9617-x)

>10. **Ward, E.J.**, H. Chirrakal, M. González-Suárez, D. Aurioles-Gamboa, E.E. Holmes, L. Gerber. 2010. Applying Multivariate state-space models to detect spatial clustering of California sea lions in the Gulf of California, Mexico. *Journal of Applied Ecology*, 47: 47-56. *Recommended by Faculty of 1000 Biology* [link](http://onlinelibrary.wiley.com/store/10.1111/j.1365-2664.2009.01745.x/asset/j.1365-2664.2009.01745.x.pdf?v=1&t=iq132i5l&s=c445f6b7a3f6758b10909a2fb46a9acce9f0eb71)

>9. Semmens, B.X., **E.J. Ward**, J.W. Moore, and C.T. Darimont. 2009. Quantifying inter- and intra-population niche variability using hierarchical Bayesian stable isotope mixing models. *PLoS ONE*, 4(7): e6187. *joint 1st authorship* [link](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006187)

>8. **Ward, E.J.**, E.E. Holmes, and K.C. Balcomb. 2009. Quantifying the effects of prey abundance on killer whale reproduction. *Journal of Applied Ecology*, 46(3): 632-640. [link](http://onlinelibrary.wiley.com/store/10.1111/j.1365-2664.2009.01647.x/asset/j.1365-2664.2009.01647.x.pdf?v=1&t=ipzzemtm&s=1ed6c77f733c00c0b0c752eb310792c73d252ae4)

>7. Semmens, B.X., J. Moore, and **E.J. Ward**. 2009. Improving Bayesian isotope mixing models: a response to Jackson et al. *Ecology Letters*, 12(3): E6-E8. [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1461-0248.2009.01283.x/abstract)

>6. **Ward, E.J.**, E.E. Holmes, K. Parsons, KC Balcomb, and JKB Ford. 2009. The role of menopause and reproductive senescence in a long-lived social mammal. *Frontiers in Zoology*, 6(4). [link](http://frontiersinzoology.biomedcentral.com/articles/10.1186/1742-9994-6-4)

>5. **Ward, E.J.** 2008. A review and comparison of four commonly used Bayesian and maximum likelihood model selection tools. *Ecological Modelling*, 211: 1-10.  [link](http://www.sciencedirect.com/science/article/pii/S0304380007005558)

>4. **Ward, E.J.**, R. Hilborn, R.G. Towell, and L. Gerber. 2007. A state-space mixture approach for estimating catastrophic events in time series data. *Canadian Journal of Fisheries and Aquatic Sciences*, 64: 899-910. [link](http://www.nrcresearchpress.com/doi/pdf/10.1139/f07-060)

>3. **Ward, E.J.** 2006. A new BEAST: Bayesian software tools for ecological trend analysis. *Wildlife Society Bulletin*, 34: 1420-1424. [link](http://www.bioone.org/doi/abs/10.2193/0091-7648(2006)34%5B1420%3AANBBST%5D2.0.CO%3B2)

>2. Branch, T., A. Haynie, R. Hilborn, G. Fay, L. Flynn, J. Griffiths, K. Marshall, J. Randall, J. Scheurell, **E.J. Ward**, and M. Young. 2006. Fleet dynamics and fishermen behavior: lessons for fisheries managers. *Canadian Journal of Fisheries and Aquatic Sciences*, 63: 1647-1668. [link](http://www.nrcresearchpress.com/doi/abs/10.1139/f06-072#.V3Lu1OYrKi4)

>1. **Ward, E.J.** 2005. Differences between fishery-dependent and fishery-independent estimates of single-species and mixed-species dolphin schools: implications for single-species stock assessments. *Marine Mammal Science*, 21: 189-203. [link](http://onlinelibrary.wiley.com/doi/10.1111/j.1748-7692.2005.tb01223.x/abstract)

# Technical Reports

>12. Ferguson, L., M. Srinivasan, E. Oleson, S. Hayes, S.K. Brown, R. Angliss, J. Carretta, E. Holmes, **E.J. Ward**, J. Kocik, K. Mullin, R. Dean, and J. Davis (eds.). 2017. Proceedings of the First National Protected Species Assessment Workshop. U.S. Dept. of Commer., NOAA. NOAA Technical Memorandum NMFS-F/SPO-172, 92 p. [link](http://spo.nmfs.noaa.gov/sites/default/files/TMSPO172.pdf)

>11. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2016 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>10. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2016 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>9. Gustafson, R.G., L. Weitkamp, Y.W. Lee, **E.J. Ward**, K. Somers, V. Tuttle, and J. Jannot. 2016. Status Review Update of Eulachon (Thaleichthys pacificus) Listed under the Endangered Species Act: Southern Distinct Population Segment. [link](http://www.westcoast.fisheries.noaa.gov/publications/status_reviews/other_species/eulachon/eulachon_2016_status_review_update.pdf)

>8. Gerrodette, T., **E.J. Ward**, R.L. Taylor, L.K. Schwarz, T. Eguchi, P.R. Wade, and G.K. Himes-Boor. 2016. Daniel Goodman’s empirical approach to Bayesian statistics. Pre-print at PeerJ [link](https://peerj.com/preprints/1755/)

>7. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2015 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>6. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2015 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>5. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2014 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>4. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2014 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data.

>3. **E.J. Ward**, M.J. Ford, R.G. Kope, J.K.B. Ford, A. Velez-Espino, C.K. Parken, L. LaVoy, M.B. Hanson, K.C. Balcomb. Estimating the impacts of Chinook salmon abundance and prey removal by ocean fishing on Southern Resident killer whale population dynamics. 2013. U.S. Dept. Commer., NOAA Tech. Memo. NMFS-NWFSC-123, 71 p. [link](https://www.nwfsc.noaa.gov/assets/25/4647_08132013_113012_ImpactsOnSRKWsTM123WebFinal.pdf)

>2. Stout, H.A., P.W. Lawson, D.L. Bottom, T.D. Cooney, M.J. Ford, C.E. Jordan, R.G. Kope, L.M. Kruzic, G.R. Pess, G.H. Reeves, M.D. Scheuerell, T.C. Wainwright, R.S. Waples, **E.J. Ward**, L.A. Weitkamp, J.G. Williams, and T.H. Williams. 2012. Scientific conclusions of the status review for Oregon coast coho salmon (Oncorhynchus kisutch). U.S. Dept. Commer., NOAA Tech. Memo. NMFS-NWFSC-118, 242 p. [link](https://www.nwfsc.noaa.gov/assets/25/1916_08132012_121939_SROregonCohoTM118WebFinal.pdf)

>1. Northwest Fisheries Science Center. 2011. Risk assessment of U.S. West Coast groundfish fisheries to threatened and endangered marine species. NWFSC, NMFS. 2725 Montlake Blvd E, Seattle, WA. [link](https://www.nwfsc.noaa.gov/assets/11/4242_07142014_135038_Ford.et.al.2012.pdf)

# Book Chapters

**E.J. Ward** 2012. Population Dynamics. In *Grzimek’s Animal Life Encyclopedia*. pp. 195-
208.

# Teaching Experience

*FISH 507: Applied Time Series Analysis*, University of Washington \hfill 2012 - present
\newline Co-taught course with Eli Holmes and Mark Scheuerell [webpage](https://catalyst.uw.edu/workspace/fish203/35553/)

*Ecological Society of America (ESA)* \hfill 2008 - 2011
\newline Co-taught Analysis of Multivariate Time-Series Data Using State-Space Models, and Introduction to MARSS

*NWFSC R workshop* (organized & taught) \hfill 2010 - 2011

*Visiting lecturer* University of Washington \hfill 2007 - 2009
\newline Taught FSH 497 Introductory modeling and programming course

# External Funding

**2018-2020** G. Holtgrieve, C. Harvey, and E.J. Ward. *Reconstructing a Century of Coastal Productivity and Predator Trophic Dynamics using Compound-specific Stable Isotopes from Archival Bone Specimens*. Washington Sea Grant, $192K.

**2018-2020** L. Hauser, B. Vadopalas, R. Childer, B. Hudson, B. Eudeline, and E.J. Ward. *Development of genetic risk assessment tools and Management Strategy Evaluation for Aquaculture of Native Shellfish*. Saltonstall-Kennedy Grant, $299K.

**2017-2018** E.J. Ward, G. Holtgrieve, C. Harvey. *Reconstructing a ecosystem productivity and marine mammal trophic dynamics using compound-specific stable isotopes from bone specimens*. NWFSC Internal Grants Program

**2016-2018** T.E. Essington, T.B. Francis, C. Greene, L. Kuehne, D. Lowry, E.J. Ward. *Recovering historical baselines in Puget Sound*. Washington Sea Grant, $243K.

**2016** E.J. Ward *Improving bycatch estimation through spatial statistics* $100K.

**2015** E.J. Ward, A.O. Shelton and M.J. Ford. *Portfolio Effects in Historic Chinook Hatchery Practices on Prey Availability for Southern Resident Killer Whales* National Fish and Wildlife Foundation, $110K.  

**2014-2015** I. Kaplan, E.J. Ward, et al. *A spatially explicit ecosystem model for quantifying marine mammal impacts on Chinook salmon* Pacific Salmon Commission Southern Fund, $206K.  

**2013-2014** T. Eguchi, E.J. Ward, and E.E. Holmes. *Developing risk assessment tools for marine sea turtles* $100K.

**2013-2014** Holmes, E.E. and E.J. Ward. *Developing web based computing tools for protected species*. $200K.

**2013** M.B. Hanson, E.J. Ward. et al. *Modeling the distribution of endangered killer whales in Pacific Northwest Navy ranges using acoustic recorder detections and satellite tagged whales*, US Navy. 

**2013** Shelton, A.O., E.J. Ward, J.T. Thorson, M. Bellman, B. Feist. *Integrating spatial habitat and fisheries effort data to improve abundance estimates of west coast groundfish*. $56K.

**2011** E.J. Ward et al., *Incorporating multiple data sources into a unified framework to improve estimates of adult salmon returns and population productivity*. $33K.

**2009** *NSF Comparative Analysis of Marine Ecosystem Organization: New statistical tools for analyzing community dynamics with applications to marine zooplankton*, $347K (141K from NCEAS). Associate Investigator (Principal Investigator - E.E. Holmes)

# Fellowships and Awards

**2006** *Cumulative Risk Assessment for Endangered Species* 2 year NRC post-doc awarded $92K.

**2003** *National Marine Fisheries Service / Washington Sea Grant Fellowship in Population Dynamics*: Incorporating model selection and decision analysis into population dynamics modeling. Grant awarded for $120K.

# Post-docs

**2012** Jim Thorson (NRC Research Post-doc). With Michelle McClure, Eli Holmes, and Mark Scheuerell  

**2012-2013** Guillaume Bal (NRC Research Post-doc). Co-supervised with Eli Holmes and Mark Scheuerell 

**2015-2017** Sean Anderson (Smith Fellow). Co-supervised with Trevor Branch

**2017--** Ben Nelson (NWFSC). Co-supervised with Ole Shelton

**2017--** Lewis Barnett (NWFSC) 

# Supervised Graduate	Students or	Committees

**2017--** Natalie Lowell (L. Hauser), SAFS, University of Washington

**2017--** Megan Feddern (G. Holtgrieve), SAFS, University of Washington

**2012-2017** Pam Moriarty (T. Essington), SAFS, University of Washington

**2013-2016** Brandon Chasco (S. Heppell) Oregon State University

**2014-2015** Brian Stock (B. Semmens) SIO, with Tomo Eguchi

**2015-2016** Hannah Linder (J. Horne) UW

# Service and Outreach

**Subject Editor, Ecological Applications** \hfill 2013 - present  
  
**Puget Sound Seabird Survey** \hfill 2005-present
\newline Developed survey methodology for Puget Sound’s first land-based citizen science seabird survey and oversaw data analysis

**Orca Bowl** Washington State Sea Grant / University of Washington

**Secretary & Treasurer**, Statistical Ecology Section, Ecological Society of America 2010-2012
